# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('descripcio', models.TextField()),
                ('unitat', models.CharField(choices=[('EUR', 'Euros'), ('DIA', 'Dies'), ('PCT', 'Percentatge')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Objectiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projecte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('descripcio', models.TextField()),
                ('presupost', models.FloatField()),
                ('estat', models.CharField(choices=[('PE', 'Pendent'), ('PR', 'Progres'), ('RE', 'Rebutjat'), ('FI', 'Finalitzat')], max_length=2)),
                ('inici', models.DateField(auto_now=True)),
                ('final', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.FloatField()),
                ('comentari', models.TextField()),
                ('data', models.DateField(auto_now=True)),
                ('projecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projecte')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projecte',
            name='usuari',
            field=models.ManyToManyField(through='projects.Valoracio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metrica',
            name='objectiu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metriques_objectius', to='projects.Objectiu'),
        ),
    ]
