# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecte',
            name='tipus',
            field=models.CharField(choices=[('F2P', 'Free To Play'), ('CO', 'Convencional'), ('ALT', 'Altres')], default='CO', max_length=3),
        ),
    ]
