# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrica',
            old_name='objectiu_id',
            new_name='objectiu',
        ),
    ]
