# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160422_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecte',
            name='final',
        ),
        migrations.RemoveField(
            model_name='projecte',
            name='inici',
        ),
        migrations.RemoveField(
            model_name='projecte',
            name='usuari',
        ),
        migrations.RemoveField(
            model_name='valoracio',
            name='data',
        ),
        migrations.RemoveField(
            model_name='valoracio',
            name='usuari',
        ),
        migrations.AddField(
            model_name='projecte',
            name='objectiu',
            field=models.ManyToManyField(through='projects.Valoracio', to='projects.Objectiu'),
        ),
        migrations.AddField(
            model_name='valoracio',
            name='objectiu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Objectiu'),
        ),
    ]
