# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160518_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecte',
            name='data_fi',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='data_inici',
            field=models.DateTimeField(null=True),
        ),
    ]
