# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160519_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='valor',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
