# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160423_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darrera_valoracio', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Principi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('valoracio', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AddField(
            model_name='historial',
            name='principi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Principi'),
        ),
        migrations.AddField(
            model_name='historial',
            name='projecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projecte'),
        ),
    ]
