# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_metrica_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='ponderacio',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='maxim',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='minim',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='valor',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
