# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_metrica_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('nom', models.CharField(max_length=30)),
                ('uri', models.CharField(max_length=30)),
                ('tipus', models.CharField(choices=[('ME', 'M\xe8trica'), ('OB', 'Objectiu'), ('EV', 'Evaluaci\xf3')], max_length=2)),
                ('color', models.CharField(choices=[('R', 'rojo'), ('A', 'amarillo'), ('V', 'verde')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='metrica',
            name='ponderacio',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='maxim',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='minim',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='unitat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='valor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='metrica',
            field=models.ManyToManyField(related_name='alerta_metrica', to='projects.Metrica'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='projecte',
            field=models.ManyToManyField(related_name='alerta_projecte', to='projects.Projecte'),
        ),
    ]
