# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160428_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='principi',
            name='projecte',
            field=models.ManyToManyField(through='projects.Historial', to='projects.Projecte'),
        ),
    ]
