# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_principi_projecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='unitat',
            field=models.CharField(choices=[('EUR', 'Euros'), ('DIA', 'Dies'), ('PCT', 'Percentatge')], max_length=11),
        ),
    ]
