# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160528_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='unitat',
            field=models.CharField(max_length=100),
        ),
    ]
