# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160502_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio_responsabilitat', models.PositiveSmallIntegerField()),
                ('puntuacio_estrategia', models.PositiveSmallIntegerField()),
                ('puntuacio_adquisicio', models.PositiveSmallIntegerField()),
                ('puntuacio_rendiment', models.PositiveSmallIntegerField()),
                ('puntuacio_conformitat', models.PositiveSmallIntegerField()),
                ('puntuacio_conducta', models.PositiveSmallIntegerField()),
                ('comentari_responsabilitat', models.TextField()),
                ('comentari_estrategia', models.TextField()),
                ('comentari_adquisicio', models.TextField()),
                ('comentari_rendiment', models.TextField()),
                ('comentari_conformitat', models.TextField()),
                ('comentari_conducta', models.TextField()),
                ('projecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projecte')),
            ],
        ),
        migrations.RemoveField(
            model_name='historial',
            name='principi',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='projecte',
        ),
        migrations.RemoveField(
            model_name='principi',
            name='projecte',
        ),
        migrations.RemoveField(
            model_name='principi',
            name='valoracio',
        ),
        migrations.AddField(
            model_name='principi',
            name='objectiu',
            field=models.ManyToManyField(related_name='principis_objectius', to='projects.Objectiu'),
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
