# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projecte_maxim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='uri',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objectiu',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='principi',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
