# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160506_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacio',
            name='data_modificacio',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 6, 14, 29, 20, 281462, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
