# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160506_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracio',
            name='creat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='valoracio',
            name='modificat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacio',
            name='creat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacio',
            name='modificat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='creat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='modificat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
