# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160509_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='maxim',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metrica',
            name='minim',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projecte',
            name='data_fi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projecte',
            name='data_inici',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projecte',
            name='maxim',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projecte',
            name='minim',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projecte',
            name='tipus',
            field=models.CharField(choices=[('F2P', 'Free To Play'), ('CO', 'Convencional'), ('ALT', 'Altres')], default='CO', max_length=2),
        ),
    ]
